- id: 7804932443414dc3befb65bf59979a2d
  alias: '[tv] input_boolean tvbert_plex uit na 2sec'
  trigger:
  - entity_id: input_boolean.tvbert_plex
    for:
      seconds: '2'
    platform: state
    to: 'on'
  action:
  - entity_id: input_boolean.tvbert_plex
    service: input_boolean.turn_off
  initial_state: true
- id: a50b77ed93484a09a7fcaed84dbb0148
  alias: '[tv] Plex op TV Bert'
  trigger:
  - entity_id: input_boolean.tvbert_plex
    platform: state
    to: 'on'
  action:
  - data:
      payload: plex
      topic: cmnd/tvbert/run
    service: mqtt.publish
  initial_state: true
- id: 14e903d5444b4b279b5d92954671a367
  alias: '[tv] input_boolean tvbert_youtube uit na 2sec'
  trigger:
  - entity_id: input_boolean.tvbert_youtube
    for:
      seconds: '2'
    platform: state
    to: 'on'
  action:
  - entity_id: input_boolean.tvbert_youtube
    service: input_boolean.turn_off
  initial_state: true
- id: e9dc002bd0e642278d05958a7843fe80
  alias: '[tv] YouTube op TV Bert'
  trigger:
  - entity_id: input_boolean.tvbert_youtube
    platform: state
    to: 'on'
  action:
  - data:
      payload: youtube
      topic: cmnd/tvbert/run
    service: mqtt.publish
  initial_state: true
- id: 752e2e1a28194a0e992c5083afd393fe
  alias: '[tv] input_boolean tvbert_itv uit na 2sec'
  trigger:
  - entity_id: input_boolean.tvbert_itv
    for:
      seconds: '2'
    platform: state
    to: 'on'
  action:
  - entity_id: input_boolean.tvbert_itv
    service: input_boolean.turn_off
  initial_state: true
- id: 9ec572b26362426da82ac67778ec0a94
  alias: '[tv] KPN iTV online op TV Bert'
  trigger:
  - entity_id: input_boolean.tvbert_itv
    platform: state
    to: 'on'
  action:
  - data:
      payload: itv
      topic: cmnd/tvbert/run
    service: mqtt.publish
  initial_state: true
- id: 314ee342eb894adbbafa56183ac6c614
  alias: '[tv] input_boolean tvbert_turnon uit na 2sec'
  trigger:
  - entity_id: input_boolean.tvbert_turnon
    for:
      seconds: '2'
    platform: state
    to: 'on'
  action:
  - entity_id: input_boolean.tvbert_turnon
    service: input_boolean.turn_off
  initial_state: true
- id: 1f1425feb1b544f491ccd35ece1c5bc2
  alias: '[tv] Zet TV Bert aan'
  trigger:
  - entity_id: input_boolean.tvbert_turnon
    platform: state
    to: 'on'
  action:
  - data:
      payload: turnon
      topic: cmnd/tvbert/run
    service: mqtt.publish
  initial_state: true
# ###############################################
# - alias: Mark person as Net thuis
#   id: 1391y24971y439
#   initial_state: true
#   trigger:
#     - platform: state
#       entity_id: person.bert_havekes
#       to: 'home'
#     - platform: state
#       entity_id: person.marc_havekes
#       to: 'home'
#     - platform: state
#       entity_id: person.thom_havekes
#       to: 'home'
#     - platform: state
#       entity_id: person.eddy_havekes
#       to: 'home'
#     - platform: state
#       entity_id: person.jacqueline_havekes
#       to: 'home'
#     - platform: state
#       entity_id: person.eliza_amling
#       to: 'home'
#   action:
#     - service: input_boolean.turn_on
#       data:
#         entity: input_boolean.huis_occupied
#     - service: input_select.select_option
#       data_template:
#         entity_id: >
#           {% if trigger.entity_id == 'person.bert_havekes' %}
#             input_select.bert_status
#           {% elif trigger.entity_id == 'person.marc_havekes' %}
#             input_select.marc_status
#           {% elif trigger.entity_id == 'person.thom_havekes' %}
#             input_select.thom_status
#           {% elif trigger.entity_id == 'person.eddy_havekes' %}
#             input_select.eddy_status
#           {% elif trigger.entity_id == 'person.jacqueline_havekes' %}
#             input_select.jacqueline_status
#           {% else %}
#             input_select.eliza_status
#           {% endif %}
#         option: >
#           {% if trigger.entity_id == 'person.bert_havekes' %}
#             {% if states.input_select.bert_status.state == 'Net weg' %}
#               Thuis
#             {% else %}
#               Net thuis
#             {% endif %}
#           {% elif trigger.entity_id == 'person.marc_havekes' %}
#             {% if states.input_select.marc_status.state == 'Net weg' %}
#               Thuis
#             {% else %}
#               Net thuis
#             {% endif %}
#           {% elif trigger.entity_id == 'person.thom_havekes' %}
#             {% if states.input_select.thom_status.state == 'Net weg' %}
#               Thuis
#             {% else %}
#               Net thuis
#             {% endif %}
#           {% elif trigger.entity_id == 'person.eddy_havekes' %}
#             {% if states.input_select.eddy_status.state == 'Net weg' %}
#               Thuis
#             {% else %}
#               Net thuis
#             {% endif %}
#           {% elif trigger.entity_id == 'person.jacqueline_havekes' %}
#             {% if states.input_select.jacqueline_status.state == 'Net weg' %}
#               Thuis
#             {% else %}
#               Net thuis
#             {% endif %}
#           {% elif trigger.entity_id == 'person.eliza_amling' %}
#             {% if states.input_select.eliza_status.state == 'Net weg' %}
#               Thuis
#             {% else %}
#               Net thuis
#             {% endif %}
#           {% endif %}
# #######################################################
# - alias: Mark person as Thuis
#   id: 9r98e9ri9weri0q
#   initial_state: true
#   trigger:
#     - platform: state
#       entity_id: input_select.bert_status
#       to: 'Net thuis'
#       for:
#         minutes: 10
#     - platform: state
#       entity_id: input_select.marc_status
#       to: 'Net thuis'
#       for:
#         minutes: 10
#     - platform: state
#       entity_id: input_select.thom_status
#       to: 'Net thuis'
#       for:
#         minutes: 10
#     - platform: state
#       entity_id: input_select.eddy_status
#       to: 'Net thuis'
#       for:
#         minutes: 10
#     - platform: state
#       entity_id: input_select.jacqueline_status
#       to: 'Net thuis'
#       for:
#         minutes: 10
#     - platform: state
#       entity_id: input_select.eliza_status
#       to: 'Net thuis'
#       for:
#         minutes: 10
#     - platform: state
#       entity_id: input_select.bert_status
#       from: 'Net weg'
#       to: 'Net thuis'
#     - platform: state
#       entity_id: input_select.marc_status
#       from: 'Net weg'
#       to: 'Net thuis'
#     - platform: state
#       entity_id: input_select.thom_status
#       from: 'Net weg'
#       to: 'Net thuis'
#     - platform: state
#       entity_id: input_select.eddy_status
#       from: 'Net weg'
#       to: 'Net thuis'
#     - platform: state
#       entity_id: input_select.jacqueline_status
#       from: 'Net weg'
#       to: 'Net thuis'
#     - platform: state
#       entity_id: input_select.eliza_status
#       from: 'Net weg'
#       to: 'Net thuis'
#   action:
#     - service: input_select.select_option
#       data_template:
#         entity_id: >
#           {% if trigger.entity_id == 'input_select.bert_status' %}
#             input_select.bert_status
#           {% elif trigger.entity_id == 'input_select.marc_status' %}
#             input_select.marc_status
#           {% elif trigger.entity_id == 'input_select.thom_status' %}
#             input_select.thom_status
#           {% elif trigger.entity_id == 'input_select.eddy_status' %}
#             input_select.eddy_status
#           {% elif trigger.entity_id == 'input_select.jacqueline_status' %}
#             input_select.jacqueline_status
#           {% else %}
#             input_select.eliza_status
#           {% endif %}
#         option: Thuis
# #################################################################
# - alias: Mark person as Net weg
#   id: 9re90r203989
#   initial_state: true
#   trigger:
#     - platform: state
#       entity_id: person.bert_havekes
#       from: 'home'
#     - platform: state
#       entity_id: person.marc_havekes
#       from: 'home'
#     - platform: state
#       entity_id: person.thom_havekes
#       from: 'home'
#     - platform: state
#       entity_id: person.eddy_havekes
#       from: 'home'
#     - platform: state
#       entity_id: person.jacqueline_havekes
#       from: 'home'
#     - platform: state
#       entity_id: person.eliza_amling
#       from: 'home'
#   action:
#     - service: input_select.select_option
#       data_template:
#         entity_id: >
#           {% if trigger.entity_id == 'person.bert_havekes' %}
#             input_select.bert_status
#           {% elif trigger.entity_id == 'person.marc_havekes' %}
#             input_select.marc_status
#           {% elif trigger.entity_id == 'person.thom_havekes' %}
#             input_select.thom_status
#           {% elif trigger.entity_id == 'person.eddy_havekes' %}
#             input_select.eddy_status
#           {% elif trigger.entity_id == 'person.jacqueline_havekes' %}
#             input_select.jacqueline_status
#           {% else %}
#             input_select.eliza_status
#           {% endif %}
#         option: Net weg
# ######################################################
# - alias: Mark person as Weg
#   id: dijfidfjifj
#   initial_state: true
#   trigger:
#     - platform: state
#       entity_id: input_select.bert_status
#       to: 'Net weg'
#       for:
#         minutes: 10
#     - platform: state
#       entity_id: input_select.marc_status
#       to: 'Net weg'
#       for:
#         minutes: 10
#     - platform: state
#       entity_id: input_select.thom_status
#       to: 'Net weg'
#       for:
#         minutes: 10
#     - platform: state
#       entity_id: input_select.eddy_status
#       to: 'Net weg'
#       for:
#         minutes: 10
#     - platform: state
#       entity_id: input_select.jacqueline_status
#       to: 'Net weg'
#       for:
#         minutes: 10
#     - platform: state
#       entity_id: input_select.eliza_status
#       to: 'Net weg'
#       for:
#         minutes: 10
#   action:
#     - service: input_select.select_option
#       data_template:
#         entity_id: >
#           {% if trigger.entity_id == 'input_select.bert_status' %}
#             input_select.bert_status
#           {% elif trigger.entity_id == 'input_select.marc_status' %}
#             input_select.marc_status
#           {% elif trigger.entity_id == 'input_select.thom_status' %}
#             input_select.thom_status
#           {% elif trigger.entity_id == 'input_selecteddy_status' %}
#             input_select.eddy_status
#           {% elif trigger.entity_id == 'input_select.jacqueline_status' %}
#             input_select.jacqueline_status
#           {% else %}
#             input_select.eliza_status
#           {% endif %}
#         option: Weg"
# ##################################################
# - alias: Mark person as Lang weg
#   id: 9riu9euw9gfuj
#   initial_state: true
#   trigger:
#     - platform: state
#       entity_id: input_select.bert_status
#       to: 'Weg'
#       for:
#         hours: 24
#     - platform: state
#       entity_id: input_select.marc_status
#       to: 'Weg'
#       for:
#         hours: 24
#     - platform: state
#       entity_id: input_select.thom_status
#       to: 'Weg'
#       for:
#         hours: 24
#     - platform: state
#       entity_id: input_select.eddy_status
#       to: 'Weg'
#       for:
#         hours: 24
#     - platform: state
#       entity_id: input_select.jacqueline_status
#       to: 'Weg'
#       for:
#         hours: 24
#     - platform: state
#       entity_id: input_select.eliza_status
#       to: 'Weg'
#       for:
#         hours: 24
#   action:
#     - service: input_select.select_option
#       data_template:
#         entity_id: >
#           {% if trigger.entity_id == 'input_select.bert_status' %}
#             input_select.bert_status
#           {% elif trigger.entity_id == 'input_select.marc_status' %}
#             input_select.marc_status
#           {% elif trigger.entity_id == 'input_select.thom_status' %}
#             input_select.thom_status
#           {% elif trigger.entity_id == 'input_selecteddy_status' %}
#             input_select.eddy_status
#           {% elif trigger.entity_id == 'input_select.jacqueline_status' %}
#             input_select.jacqueline_status
#           {% else %}
#             input_select.eliza_status
#           {% endif %}
#         option: Lang weg
# ########################################################################
# - alias: Mark person as School
#   id: jvfnejvmjvm
#   initial_state: true
#   trigger:
#     - platform: state
#       entity_id: person.bert_havekes
#       to: 'HHS'
#     - platform: state
#       entity_id: person.thom_havekes
#       to: 'Scala Sacharov'
#     - platform: state
#       entity_id: person.eliza_amling
#       to: 'HS Leiden'
#   action:
#     - service: input_select.select_option
#       data_template:
#         entity_id: >
#           {% if trigger.entity_id == 'person.bert_havekes' %}
#             input_select.bert_status
#           {% elif trigger.entity_id == 'person.thom_havekes' %}
#             input_select.thom_status
#           {% else %}
#             input_select.eliza_status
#           {% endif %}
#         option: School
# ########################################################################
# - alias: Mark person as Werk
#   id: jvfnejvmjvm
#   initial_state: true
#   trigger:
#     - platform: state
#       entity_id: person.bert_havekes
#       to: 'Dirk'
#     - platform: state
#       entity_id: person.thom_havekes
#       to: 'Dirk'
#     - platform: state
#       entity_id: person.eddy_havekes
#       to: 'Auma Benelux'
#     - platform: state
#       entity_id: person.jacqueline_havekes
#       to: 'Dirk'
#     - platform: state
#       entity_id: person.eliza_amling
#       to: 'Kruidvat'
#   action:
#     - service: input_select.select_option
#       data_template:
#         entity_id: >
#           {% if trigger.entity_id == 'person.bert_havekes' %}
#             input_select.bert_status
#           {% elif trigger.entity_id == 'person.thom_havekes' %}
#             input_select.thom_status
#           {% elif trigger.entity_id == 'person.eddy_havekes' %}
#             input_select.eddy_status
#           {% elif trigger.entity_id == 'person.jacqueline_havekes' %}
#             input_select.jacqueline_status
#           {% else %}
#             input_select.eliza_status
#           {% endif %}
#         option: Werk