- id: 7804932443414dc3befb65bf59979a2d
  alias: '[tv] input_boolean tvbert_plex uit na 2sec'
  trigger:
  - entity_id: input_boolean.tvbert_plex
    for:
      seconds: '2'
    platform: state
    to: 'on'
  action:
  - entity_id: input_boolean.tvbert_plex
    service: input_boolean.turn_off
  initial_state: true
- id: a50b77ed93484a09a7fcaed84dbb0148
  alias: '[tv] Plex op TV Bert'
  trigger:
  - entity_id: input_boolean.tvbert_plex
    platform: state
    to: 'on'
  action:
  - data:
      payload: plex
      topic: cmnd/tvbert/run
    service: mqtt.publish
  initial_state: true
- id: 14e903d5444b4b279b5d92954671a367
  alias: '[tv] input_boolean tvbert_youtube uit na 2sec'
  trigger:
  - entity_id: input_boolean.tvbert_youtube
    for:
      seconds: '2'
    platform: state
    to: 'on'
  action:
  - entity_id: input_boolean.tvbert_youtube
    service: input_boolean.turn_off
  initial_state: true
- id: e9dc002bd0e642278d05958a7843fe80
  alias: '[tv] YouTube op TV Bert'
  trigger:
  - entity_id: input_boolean.tvbert_youtube
    platform: state
    to: 'on'
  action:
  - data:
      payload: youtube
      topic: cmnd/tvbert/run
    service: mqtt.publish
  initial_state: true
- id: 752e2e1a28194a0e992c5083afd393fe
  alias: '[tv] input_boolean tvbert_itv uit na 2sec'
  trigger:
  - entity_id: input_boolean.tvbert_itv
    for:
      seconds: '2'
    platform: state
    to: 'on'
  action:
  - entity_id: input_boolean.tvbert_itv
    service: input_boolean.turn_off
  initial_state: true
- id: 9ec572b26362426da82ac67778ec0a94
  alias: '[tv] KPN iTV online op TV Bert'
  trigger:
  - entity_id: input_boolean.tvbert_itv
    platform: state
    to: 'on'
  action:
  - data:
      payload: itv
      topic: cmnd/tvbert/run
    service: mqtt.publish
  initial_state: true
- id: 314ee342eb894adbbafa56183ac6c614
  alias: '[tv] input_boolean tvbert_turnon uit na 2sec'
  trigger:
  - entity_id: input_boolean.tvbert_turnon
    for:
      seconds: '2'
    platform: state
    to: 'on'
  action:
  - entity_id: input_boolean.tvbert_turnon
    service: input_boolean.turn_off
  initial_state: true
- id: 1f1425feb1b544f491ccd35ece1c5bc2
  alias: '[tv] Zet TV Bert aan'
  trigger:
  - entity_id: input_boolean.tvbert_turnon
    platform: state
    to: 'on'
  action:
  - data:
      payload: turnon
      topic: cmnd/tvbert/run
    service: mqtt.publish
  initial_state: true
- id: '1572632761881'
  alias: zolder lamp timer
  description: ''
  trigger:
  - entity_id: light.lamp_zolder
    for: 00:02:00
    platform: state
    to: 'on'
  condition: []
  action:
  - alias: ''
    data:
      entity_id: light.lamp_zolder
    service: light.turn_off
- id: '1572635259214'
  alias: lamp zolder beweging
  description: ''
  trigger:
  - entity_id: binary_sensor.sonoff_motion_sensor
    platform: state
  condition:
  - after: '17:00'
    before: '7:00'
    condition: time
  action:
  - data:
      entity_id: light.lamp_zolder
    service: light.turn_on
- id: '1574711295223'
  alias: '[thom] deur open, lamp aan'
  description: ''
  trigger:
  - entity_id: binary_sensor.deur_thom
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.lamp_thom
    service: light.turn_on
- id: '1574717691283'
  alias: '[thom] deur dicht, beweging zolder, licht uit'
  description: ''
  trigger:
  - entity_id: binary_sensor.deur_thom
    for: '3'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: binary_sensor.sonoff_motion_sensor
    state: 'on'
  action:
  - data:
      entity_id: light.lamp_thom
    service: light.turn_off
- id: '1579263183917'
  alias: '[inkt] Update counter epson zwart'
  description: ''
  trigger:
  - entity_id: sensor.epson_ink_level_black
    platform: state
  condition: []
  action:
  - data_template:
      value: "{{ states('sensor.epson_ink_level_black') }}"
    entity_id: counter.epsonzwart
    service: counter.configure
- id: '15792631839fefb17'
  alias: '[inkt] Update counter epson magenta'
  description: ''
  trigger:
  - entity_id: sensor.epson_ink_level_magenta
    platform: state
  condition: []
  action:
  - data_template:
      value: "{{ states('sensor.epson_ink_level_magenta') }}"
    entity_id: counter.epsonmagenta
    service: counter.configure
- id: '15792631grewgg83917'
  alias: '[inkt] Update counter epson geel'
  description: ''
  trigger:
  - entity_id: sensor.epson_ink_level_yellow
    platform: state
  condition: []
  action:
  - data_template:
      value: "{{ states('sensor.epson_ink_level_yellow') }}"
    entity_id: counter.epsongeel
    service: counter.configure
- id: '15792rgwgwsg63183917'
  alias: '[inkt] Update counter epson cyan'
  description: ''
  trigger:
  - entity_id: sensor.epson_ink_level_cyan
    platform: state
  condition: []
  action:
  - data_template:
      value: "{{ states('sensor.epson_ink_level_cyan') }}"
    entity_id: counter.epsoncyan
    service: counter.configure
