################################################################
# Sensors ######################################################
################################################################

- platform: syncthru # Samsung Laser printer inkt sensor
  resource: http://192.168.2.52
  name: Laser Printer
##
- platform: solaredge # Zonnepanelen sensor
  api_key: !secret solaredge_api
  site_id: !secret solaredge_side_id
  name: SolarEdge
  monitored_conditions:
    - current_power
    - energy_today
    - energy_this_month
    - energy_this_year
    - lifetime_energy
- platform: template
  sensors:
    solaredge_huidig_vermogen:
      friendly_name: "solaredge_huidig_vermogen"
      unit_of_measurement: 'W'
      value_template: '{{(states.sensor.solaredge_current_power.state)}}'
- platform: template
  sensors:
    solaredge_vandaag:
      friendly_name: "solaredge_vandaag"
      unit_of_measurement: 'Wh'
      value_template: '{{(states.sensor.solaredge_energy_today.state)}}'
- platform: template
  sensors:
    solaredge_deze_maand:
      friendly_name: "solaredge_deze_maand"
      unit_of_measurement: 'kWh'
      value_template: '{{(states.sensor.solaredge_energy_this_month.state | float / 1000) | round(2)}}'
- platform: template
  sensors:
    solaredge_dit_jaar:
      friendly_name: "solaredge_dit_jaar"
      unit_of_measurement: 'kWh'
      value_template: '{{(states.sensor.solaredge_energy_this_year.state | float / 1000) | round(2)}}'
- platform: template
  sensors:
    solaredge_totale_looptijd:
      friendly_name: "solaredge_totale_looptijd"
      unit_of_measurement: 'MWh'
      value_template: '{{(states.sensor.solaredge_lifetime_energy.state | float / 1000000) | round(3)}}'
##
- platform: steam_online # Status Steam accounts
  api_key: !secret steam_api
  accounts:
    - !secret steam_account_bert
    - !secret steam_account_marc
    - !secret steam_account_thom
    - !secret steam_account_thom2
##
- platform: postnl # PostNL pakketstatus
  username: !secret postnl_bert_username
  password: !secret postnl_bert_password

##
- platform: plex # Plex viewer status
  host: "5.132.90.5"
  port: 32400
  username: !secret plex_username
  password: !secret plex_password
  token: !secret plex_token
##
- platform: nederlandse_spoorwegen # NS treinen status
  email: !secret ns_email
  password: !secret ns_password
  routes:
  - name: Leiden-Den Haag HS
    from: Ledn
    to: Gv
  - name: Den Haag HS-Leiden
    from: Gv
    to: Ledn
##
- platform: template # Verandering benaming online/offline
  sensors:
    asusbert:
      friendly_name: "AsusBert"
      value_template: >-
        {% if is_state('binary_sensor.asusbert', 'on') %}
          Online
        {% else %}
          Offline
        {% endif %}
- platform: template
  sensors:
    serverbert:
      friendly_name: "ServerBert"
      value_template: >-
        {% if is_state('binary_sensor.serverbert', 'on') %}
          Online
        {% else %}
          Offline
        {% endif %}
##
- platform: dht # Temperatuursensor in kist
  sensor: DHT11
  pin: 4
  monitored_conditions:
    - temperature
    - humidity

- platform: filter # Filter voor mooie grafiek
  name: "dht_sensor_temperature_filter"
  entity_id: sensor.dht_sensor_temperature
  filters:
    - filter: lowpass
      precision: 0
    - filter: range
      lower_bound: 20
    - filter: outlier
      window_size: 20
      radius: 10.0

##
- platform: time_date # Wekker
  display_options:
    - 'time'
- platform: template
  sensors:
    alarm_clock_hour:
      value_template: '{{ states.input_number.alarm_clock_hour.state | int }}'
    alarm_clock_minute:
      value_template: '{{ states.input_number.alarm_clock_minute.state | int }}'
    alarm_clock_time:
      value_template: >-
        {{ states.sensor.alarm_clock_hour.state }}:
        {%- if states.sensor.alarm_clock_minute.state|length == 1 -%}
          0
        {%- endif -%}
          {{ states.sensor.alarm_clock_minute.state }}
    alarm_clock_time_long:
      value_template: >-
        {% if states.sensor.alarm_clock_hour.state|length == 1 -%}
          0
        {%- endif -%}
          {{ states.sensor.alarm_clock_hour.state }}:
        {%- if states.sensor.alarm_clock_minute.state|length == 1 -%}
          0
        {%- endif -%}
          {{ states.sensor.alarm_clock_minute.state }}
##
- platform: mqtt
  name: "TV Bert Status"
  state_topic: "stat/tvbertstatus/status"
##
- platform: template # geeft starttijd voor volgende werkdienst
  sensors:
    starttimewerk:
      friendly_name: "Start tijd werk"
      value_template: "{{ as_timestamp(strptime(state_attr('calendar.werk', 'start_time'), '%Y-%m-%d %H:%M:%S')) | timestamp_custom('%H:%M') }}"
##
- platform: time_date # datum en tijd nu
  display_options:
  - 'date_time'

- platform: template # Tijdverschil in sec. tussen starttijd werk en nu
  sensors:
    cal_alert_time:
      entity_id: sensor.date_time
      value_template: "{{ (as_timestamp(state_attr('calendar.werk', 'start_time')) - as_timestamp(now()) ) }}"
      friendly_name: 'Alert Time'
##
- platform: mqtt
  name: "Nokia Bert wekker"
  state_topic: "stat/nokiabert/wekker"
##
- platform: mqtt
  name: Bridge state
  state_topic: "zigbee2mqtt/bridge/state"
  icon: mdi:router-wireless
##
- platform: mqtt
  state_topic: "sensors/rf/receiver"
  name: "RF Receiver"
##
- platform: command_line
  name: Epson ink level Black
  command: /usr/bin/curl -k https://192.168.2.53/PRESENTATION/HTML/TOP/PRTINFO.HTML | awk -F"'" '/Ink_K.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100 }' | head -1
  unit_of_measurement: '%'
  scan_interval: 14400
- platform: command_line
  name: Epson Ink Level Magenta
  command: /usr/bin/curl -k https://192.168.2.53/PRESENTATION/HTML/TOP/PRTINFO.HTML | awk -F"'" '/Ink_M.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100 }'
  unit_of_measurement: '%'
  scan_interval: 14400
- platform: command_line
  name: Epson Ink Level Yellow
  command: /usr/bin/curl -k https://192.168.2.53/PRESENTATION/HTML/TOP/PRTINFO.HTML | awk -F"'" '/Ink_Y.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100 }'
  unit_of_measurement: '%'
  scan_interval: 14400
- platform: command_line
  name: Epson Ink Level Cyan
  command: /usr/bin/curl -k https://192.168.2.53/PRESENTATION/HTML/TOP/PRTINFO.HTML | awk -F"'" '/Ink_C.PNG/ && $6+0 == $6 { printf "%.0f\n", $6 / 50 * 100 }'
  unit_of_measurement: '%'
  scan_interval: 14400
##
- platform: rflink
#  devices:
#    elrodb_00fed593_1:
#      name: Deurbel
#      sensor_type: doorbell_melody
#    doorbell_0e68_1:
#      name: Deurbel
#      sensor_type: doorbell_melody
  automatic_add: false
##
- platform: pi_hole
  host: localhost:4865
  ssl: true
  verify_ssl: false
  monitored_conditions:
    - ads_blocked_today
    - ads_percentage_today
    - dns_queries_today
    - domains_being_blocked
    - queries_cached
    - queries_forwarded
    - unique_clients
    - unique_domains
    - clients_ever_seen
##
- platform: ovapi
  name: Bus 182 Ter Aar
  timing_point_code: 54441000
  line_filter: 182
- platform: ovapi
  name: Bus 182 Leiden
  timing_point_code: 54732091
##
- platform: seventeentrack
  username: !secret 17trackuser
  password: !secret 17trackpass
##
# - platform: pushbullet
#   api_key: !secret pushbulletbert
##
- platform: afvalbeheer
  wastecollector: Cyclus
  resources:
    - restafval
    - gft
    - papier
    - pmd
  postcode: 2461TG
  streetnumber: 47
  upcomingsensor: 1
  dateformat: '%d %b'
  dateonly: 1
  nameprefix: 0
  builtinicons: 0
#
- platform: template
  sensors:
    alarm_time_werk: # starttijd werk uit agenda, -offset van input_number
      friendly_name: "Alarm tijd werk"
      value_template: '{{ (as_timestamp(states.calendar.werk.attributes.start_time) + (states("input_number.werk_tijd_offset") | int) * 60) | timestamp_custom("%H:%M") }}'
